name: SelfClosingDoors
main: com.yurijware.bukkit.selfclosingdoors.SelfClosingDoors
version: 1.1
website: 
author: Yurij @ YurijWare
description: >
             Closes wooden doors a certain time after opening them
